name: Mirror the repo to disroot
on: [push]

jobs:
  disroot-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: mirror in git.disroot
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://git.disroot.org/archy-linux/archy-dwm.git'
          REMOTE_NAME: disroot
          GIT_USERNAME: anas-elgarhy
          GIT_PASSWORD: ${{ secrets.DISROOT_TOKEN }}
