name: Mirror the repo to gitlab
on: [push]

jobs:
  gitlab-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: mirror in gitlab
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://gitlab.com/archy-linux/archy-dwm'
          GIT_USERNAME: Anas-Elgarhy
          GIT_PASSWORD: ${{ secrets.GITLAP_TOKEN }}
