name: Mirror the repo to pagure
on: [ push ]

jobs:
  gitdab-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: mirror in Gitdab
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://gitdab.com/archy-linux/archy-dwm.git'
          REMOTE_NAME: gitdab
          GIT_USERNAME: anas-elgarhy

